version: "3"
services:
    frontend:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: client1
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server1
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app
networks:
  default:
    external:
      name: your-network
